### PR TITLE
Start with trying to spec foreign fetch.

### PR DESCRIPTION
**Pull request by mkruisselbrink**
My attempt to spec the API described in issue #684.

I don't think this is anywhere near ready to be merged yet (in only because as far as I know current master is still V1, and this definitely is a V2 feature), but a pull request seemed like the easiest way to have a place to discuss details of foreign fetch.

Also haven't updated the .ts file with these changes, but then that file seems to be rather out of date anyway. So not sure if that file is still being used?

### CODE REVIEW

**Comment by annevk** [comment]
@jungkees did you read OP? "I don't think this is anywhere near ready to be merged yet"...

**Comment by jungkees** [comment]
@mkruisselbrink was waiting for V1 branching out. I reviewed and merged this PR to the nightly version. I think it's okay. A few minor fixes seem to be needed which I'll take care.

**Comment by jungkees** [comment]
@mkruisselbrink thanks for the excellent text. I made minor changes especially in `InstallEvent` and its `event.registerForeignFetchScopes(subScopes)` steps. Note that I changed the parameter type of the method to `sequence<USVString>` in order to maintain consistency with other methods (such as `cache.addAll(sequence<RequestInfo> requests)`) in the spec.

**Comment by wanderview** [comment]
It still seems some time to review and discuss before merging to spec would be nice.

**Comment by jungkees** [comment]
Agreed and reverted the merge manually (3cc01eece9b5756069f7bcc344abeba1eceffc2f) as I had already put some changes on it.

My apologies @mkruisselbrink. Could you make a PR again to the nightly version (the same file you made one)? Let's discuss and work on it. Thanks!

**Pull request merged**
