### PR TITLE
Run the latest Bikeshed

### PR DESCRIPTION
**Pull request by yutakahirano**
Run Bikeshed in order to keep the subsequent change clean.

### CODE REVIEW

**Comment by yutakahirano** [comment]
Should I run Bikeshed for /spec/service_worker_1 as well?

**Comment by domenic** [comment]
It seems like some collaborators are not using the latest Bikeshed so this gets reset every other commit, which is frustrating.

**Comment by annevk** [comment]
Probably @jungkees has not updated his copy (in the bikeshed directory: git pull; bikeshed update).

**Comment by jungkees** [comment]
Sorry. It was me. I didn't realize I'm doing it wrong. I'll do bikeshed update before processing documents from this point on. Thanks for letting me know.

**Pull request merged**
